flagforge:
  redis:
    uri: ${REDIS_URI:redis://localhost:6379}
  security:
    jwt:
      secret: ${FLAGFORGE_JWT_SECRET:4407a837731d92425e627e49632afbabd538a25e080fafed65a9ff7e71a9f5d1}
      expiration_duration_seconds: 7200
    cors:
      allowed-origins: ${FLAGFORGE_CORS_ALLOWED_ORIGINS:http://localhost:4200}

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: flagforge
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/flagforge}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:webapp-flagforge}
    password: ${SPRING_DATASOURCE_PASSWORD:webapp-flagforge}

  jpa:
    hibernate:
      ddl-auto: validate  # Flyway manages schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: true

springdoc:
  api-docs:
    version: openapi_3_0  # Use OpenAPI 3.0.3 for ng-openapi-gen compatibility

logging:
  structured:
    format:
      console: logstash
  level:
    root: INFO
    io.hephaistos.flagforge: INFO
