server:
  port: 8081

spring:
  application:
    name: flagforge-customer-api
  datasource:
    url: jdbc:postgresql://localhost:5432/flagforge
    driver-class-name: org.postgresql.Driver
    username: customer-flagforge
    password: customer-flagforge

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: false  # webapp-api owns migrations

springdoc:
  api-docs:
    version: openapi_3_0

logging:
  file:
    name: build/logs/flagforge-customer-api.log
  level:
    root: INFO
    io.hephaistos.flagforge: DEBUG

flagforge:
  rate-limit:
    enabled: true
    redis-uri: redis://localhost:6379
    fail-open: true
